name: XSpec

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the XSpec Docker image
      run: docker build . --file Dockerfile --tag xspec:latest
    
    - name: Run XSpec tests within Docker image
      run: docker run xspec -t xspec
