name: XSpec

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  xspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Run XSpec tests
      run: bin/batch-xspec xspec
