name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  xspec:
    name: XSpec
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Run XSpec tests
      run: bin/batch-xspec-junit xspec
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          xspec/**/*-junit.xml
